#!/bin/bash

function main() {
  local -r proxy="${1:?[ERROR] proxy not provided (http://<username>:<password>@<proxy>:<port>)}";
  local -r noproxy="localhost,127.0.0.1,localaddress,.localdomain.com";  
  # https://help.ubuntu.com/community/EnvironmentVariables#A.2Fetc.2Fenvironment
  # System-wide environment variables
  # A suitable file for environment variable settings that affect the system as a whole 
  # (rather than just a particular user) is /etc/environment. 
  # An alternative is to create a file for the purpose in the /etc/profile.d directory.
  
  # /etc/environment
  # This file is specifically meant for system-wide environment variable settings. 
  # It is not a script file, but rather consists of assignment expressions, one per line.
  # Note: Variable expansion does not work in /etc/environment!
  local -r environment="/etc/environment";
  echo "# system proxy configuration" >> "${environment}";
  echo "http_proxy=\"${proxy}\"" >> "${environment}";
  echo "https_proxy=\"${proxy}\"" >> "${environment}";
  echo "ftp_proxy=\"${proxy}\"" >> "${environment}";
  echo "no_proxy=\"${noproxy}\"" >> "${environment}";
  echo "HTTP_PROXY=\"${proxy}\"" >> "${environment}";
  echo "HTTPS_PROXY=\"${proxy}\"" >> "${environment}";
  echo "FTP_PROXY=\"${proxy}\"" >> "${environment}";
  echo "NO_PROXY=\"${noproxy}\"" >> "${environment}";
  echo "" >> "${environment}";

  # /etc/apt/apt.conf.d/
  # proxies for apt-get and Update Manager
  local -r aptconfd="/etc/apt/apt.conf.d/95proxies";
  rm -f "${aptconfd}";
  
  echo "Acquire::http::proxy \"${proxy}\";" >> "${aptconfd}";
  echo "Acquire::ftp::proxy \"${proxy}\";" >> "${aptconfd}";
  echo "Acquire::https::proxy \"${proxy}\";" >> "${aptconfd}";
  
  # /etc/profile.d/*.sh
  # Files with the .sh extension in the /etc/profile.d directory get executed whenever
  # a bash login shell is entered (e.g. when logging in from the console or over ssh), 
  # as well as by the DisplayManager when the desktop session loads.
  # Required by: Mozilla Firefox, git
  local -r profiled="/etc/profile.d/proxy.sh";
  rm -f "${profiled}";
  
  echo "# system proxy configuration" >> "${profiled}";
  echo "export http_proxy=\"${proxy}\"" >> "${profiled}";
  echo "export https_proxy=\"${proxy}\"" >> "${profiled}";
  echo "export ftp_proxy=\"${proxy}\"" >> "${profiled}";
  echo "export no_proxy=\"${noproxy}\"" >> "${profiled}";
  echo "export HTTP_PROXY=\"${proxy}\"" >> "${profiled}";
  echo "export HTTPS_PROXY=\"${proxy}\"" >> "${profiled}";
  echo "export FTP_PROXY=\"${proxy}\"" >> "${profiled}";
  echo "export NO_PROXY=\"${noproxy}\"" >> "${profiled}";
  echo "" >> "${profiled}";

}

main "$@"
