#!/bin/bash
source ./install.source.sh

function main {
  local -r filter='.[] | select(.code | contains("TBA")) | .releases[0].downloads.linux.link';
  local url;
  url=$(wget -q -O - "https://data.services.jetbrains.com/products" | jq -r "${filter}");  
  if [[ "$?" -ne 0 ]]; then
    echo "[ERROR] Unable to determine toolbox download url." >&2;
    exit 1;
  fi
  
  download "${url}" "jetbrains-toolbox" "jetbrains-toolbox";
}

main "$@";
