#!/bin/bash
source ./install.source.sh

# https://docs.docker.com/install/linux/docker-ce/ubuntu/#install-using-the-repository
function installdocker() {
  # SET UP THE REPOSITORY
  apt-get update;
  apt-get -y install \
    apt-transport-https \
    ca-certificates \
    curl \
    software-properties-common;
 curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -;
 add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable";
 
  # INSTALL DOCKER CE
  apt-get update;
  apt-get -y install docker-ce;
}

function configuredockergroup() {
  # Manage Docker as a non-root user
  # https://docs.docker.com/install/linux/linux-postinstall/
  # The docker daemon binds to a Unix socket instead of a TCP port.
  # By default that Unix socket is owned by the user root and other
  # users can only access it using sudo. The docker daemon always runs as the root user.
  # If you don’t want to use sudo when you use the docker command, create a Unix group 
  # called docker and add users to it. When the docker daemon starts, it makes 
  # the ownership of the Unix socket read/writable by the docker group.
  local -r user="${1:?[ERROR] user not provided}"
  groupadd docker;
  usermod -aG docker "${user}";
}

function configuredockerproxy() {  
  if [ -z "${http_proxy}" ]; then
    return 0;
  fi

  # Configure docker containers to use a proxy server
  # https://docs.docker.com/network/proxy/
  local -r directory=~/.docker;
  local -r file="${directory}/config.json";
  
  mkdir --mode=666 -p "${directory}";
  echo '{' >> "${file}";
  echo ' "proxies":' >> "${file}";
  echo '  {' >> "${file}";
  echo '   "default":' >> "${file}";
  echo '    {' >> "${file}";
  echo "     \"httpProxy\": \"${http_proxy}\"," >> "${file}";
  echo "     \"noProxy\": \"${no_proxy}\"" >> "${file}";
  echo '    }' >> "${file}";
  echo '  }' >> "${file}";
  echo '}' >> "${file}";
  chmod 666 "${file}";
  
  # Configure Docker daemon to use a proxy server 
  # https://docs.docker.com/config/daemon/systemd/#httphttps-proxy
  local -r daemon_config_directory="/etc/systemd/system/docker.service.d";
  local -r daemon_config_file="${daemon_config_directory}/http-proxy.conf";
  
  mkdir -p "${daemon_config_directory}";
  echo "[Service]"  >> "${daemon_config_file}";
  echo "Environment=\"HTTP_PROXY=${http_proxy}\"" >> "${daemon_config_file}";
    
  # Flush changes:
  systemctl daemon-reload
  
  # Restart Docker
  systemctl restart docker
}

function main() {
  configuredockergroup "$@";
  installdocker;
  configuredockerproxy;
}

main "$@";
