#! /bin/bash

function main {
	# https://wiki.ubuntu.com/MountWindowsSharesPermanently

	apt-get -y install cifs-utils
	#apt-get -y install nfs-utils
	
	local server=192.168.38.5
	local url=//$server/gdn01/Homes/U536884
	#local target=/mnt/lan/
	local target=./lan/home

	mkdir -p  $target
	mount -t cifs $url $tarlget -o username=U536884,password=magarana.2017,iocharset=utf8
	# mount -t cifs "$url" "$target" -o credentials=./.windowscredentials,
}

main
