#! /bin/bash
function main {
	if [ $# -ne 1 ]; then
    		echo "<user> not provided"
    		exit 1
	fi
	local user=$1;
	adduser $user sudo
	echo "$user ALL=(ALL)" NOPASSWD: ALL > /etc/sudoers.d/$user
}

main "$@"
