#!/bin/bash

function main {
  local -r path="${1:-$(pwd)}";
  cd "${path}"
  git init;
  git remote add origin https://github.com/mateuszkucharczyk/toolbox.git
  git fetch
  git reset origin/master
  git branch --set-upstream-to=origin/master master
  git fetch;
}

main "$@";
