#!/bin/bash

./install-zip
./install-java
./install-maven
./install-vcs

./install-notepad
./install-meld
./install-squirrelsql

./install-webbrowser
./install-docbrowser
./install-xmllint
./install-yed
