#!/bin/bash
source ./install.source.sh

function main() {
  local -r tmp=$(mktemp -d);
  cdorexit "${tmp}";
  
  #https://blog.bluematador.com/posts/postman-how-to-install-on-ubuntu-1604/
  wget https://dl.pstmn.io/download/latest/linux64 -O postman.tar.gz
  tar -xzf postman.tar.gz -C $(get_install_dir)
  rm postman.tar.gz
  ln -s $(get_install_dir)/Postman/Postman /usr/bin/postman
}

main "$@"
