#!/bin/bash

source ./install.source.sh

function main() {
  local -r domain="${1:?[ERROR] domain not provided}";
  local -r user="${2:?[ERROR] user not provided}";
  local -r password="${3:?[ERROR] password not provided}";

  local hash_line;
  hash_line=$(echo ${password} | cntlm -H -u${user} -d${domain} | grep PassNTLMv2);
  
  local -r config='/etc/cntlm.conf';
  if [ ! -f "${config}" ]; then
    echoerr "${config} not found!"
    return 1;
  fi

  replace_first_matching_line '\s*Domain\s.*' "Domain ${domain}" "${config}";
  replace_first_matching_line '\s*Username\s.*' "Username ${user}" "${config}";
  replace_first_matching_line '\s*PassNTLMv2\s.*' "${hash_line}" "${config}";  
  service cntlm restart;
}

main "$@"
