#!/bin/bash

./install.source.sh

function configure_cntlm() {
  local -r url="${1:?[ERROR] url not provided (http://<username>:<password>@<proxy>:<port>)}";
  local -r domain="${2:?[ERROR] domain not provided}";
  local noproxy="${3:-}";
  if [[ ! -z "${noproxy// }" ]]; then
    noproxy=", ${noproxy}";
  fi

  local -r user=$(echo ${url} | cut -d '@' -f1 | cut -d ':' -f2 | cut -c 3-);
  local -r password=$(echo ${url} | cut -d '@' -f1 | cut -d ':' -f3);
  local -r proxy=$(echo ${url} | cut -d '@' -f2);
  
  mv -f /etc/cntlm.conf /etc/cntlm.conf.backup;
  echo "Username  DUMMY" >> /etc/cntlm.conf;
  echo "Domain    DUMMY" >> /etc/cntlm.conf;
  echo "Auth        NTLMv2" >> /etc/cntlm.conf; 
  echo "PassNTLMv2 DUMMY" >> /etc/cntlm.conf;
  echo "Proxy   ${proxy}" >> /etc/cntlm.conf;
  echo 'NoProxy   localhost, 127.0.0.*, 10.*'"${noproxy}" >> /etc/cntlm.conf;
  echo "Listen    3128" >> /etc/cntlm.conf;
  echo "Gateway yes" >> /etc/cntlm.conf;
  echo "Allow       127.0.0.1" >> /etc/cntlm.conf;
  echo "Allow       10.158.3.90" >> /etc/cntlm.conf;
  echo "Allow       10.158.95.59" >> /etc/cntlm.conf;
  echo "Allow       10.200.251.25" >> /etc/cntlm.conf;
  echo "Allow       10.0.15.10" >> /etc/cntlm.conf;
  echo "Allow       192.168.56.1" >> /etc/cntlm.conf;
  echo "#Deny       0/0" >> /etc/cntlm.conf;

  ./configure-cntlm-password "${domain}" "${user}" "${password}"
}


function main() {
  apt-get update && \
  apt-get install -y cntlm && \
  service cntlm start && \
  configure_cntlm "$@" && \
  service cntlm restart;
}

main "$@"
