#!/bin/bash
source ./install.source.sh

function main() { 
  # https://linuxconfig.org/install-gui-on-ubuntu-server-18-04-bionic-beaver#h7-3-xubuntu-server-core-desktop
  # https://askubuntu.com/a/1053591
  install_from_manager tasksel && \
  apt-get install -y xubuntu-core^
  # configure-xfce is always applied to current user so we must postpone it 
  ./configure-boot-run-script-once ./configure-xfce
}

main "$@"
