#!/bin/bash
source ./install.source.sh

function main() {
  local -r user="${1:?[ERROR] user not provided}"

  ./install-java
  ./install-maven
  ./install-intellij
  ./install-docker "${user}"

  ./install-shellcheck
  
  ./install-git
  ./install-svn
  
  ./install-squirrelsql
  ./install-soapui
  ./install-postman
  
  ./install-meld
  ./install-notepad
  ./install-documentation
}

main "$@"