#!/bin/bash
source ./install.source.sh

function install_git_lfs() {
  curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash && \
  sudo apt-get install git-lfs && \
  git lfs install;
}


function install_git_core() {
  install_from_manager "git-daemon-sysvinit"
  install_from_manager "git-all"
  
  git config --system credential.helper cache;
  git config --system alias.hist "log --all --graph --decorate --oneline --follow";
  
  # use environment variables instead
  # git config --global http.proxy "${http_proxy}";
  
  # install_from_manager "giggle"
  # smartgit only for non-commercial use
  # download "http://www.syntevo.com/static/smart/download/smartgit/smartgit-linux-17_0_4.tar.gz" "smartgit" "./bin/smartgit.sh" 
}

function main() {
  install_git_core "$@";
  install_git_lfs "$@";
}

main "$@"
