#! /bin/bash

source ./install.source.sh

function main {
  local -r url="https://sourceforge.net/projects/squirrel-sql/files/1-stable/3.7.1-plainzip/squirrelsql-3.7.1-optional.zip"
  local -r name="squirrelsql"
  download "$url" "$name" "./squirrel-sql.sh"

  # install ingres jdbc driver
  local -r jdbc_path="$(get_install_dir)/${name}/jdbc";
  mkdirorexit -p "${jdbc_path}";
  download_from_maven_repository 'org.postgresql' 'postgresql' "${jdbc_path}";
  download_from_maven_repository 'com.ingres.jdbc' 'iijdbc' "${jdbc_path}";
  download_from_maven_repository 'mysql' 'mysql-connector-java' "${jdbc_path}";
}

main "$@"
