#!/bin/bash
source ./install.source.sh

function install_git_lfs() {
  local -r url='https://github.com/git-lfs/git-lfs/releases/latest';
  local -r xpath="string(//a[contains(@href,'linux-amd64')]/@href)";
  local -r tmp=$(mktemp -d);
  cdorexit "${tmp}";
  local href;
  href=$(wget -qO- "${url}" | xmllint --html --xpath "${xpath}" - 2>/dev/null);
  if [[ "$?" -ne 0 ]]; then
    echoerr "[ERROR] wget | xmllint: cannot get download link"; 
    exit 1;
  fi
  href='https://github.com'"${href}";
  
  local -r filename=$(echo "${href}" | cut -d '?' -f1 | tr '/' '\n' | tail -n1);
  wget -q -O "${filename}" "${href}";
  if [[ "$?" -ne 0 ]]; then
    echoerr "[ERROR] wget: cannot download ${filename}";  
    exit 1;
  fi
  
  local unpackdir=$(unpack_by_extension "${filename}" .);  
  local lfsscript=$(find $(pwd) -type f -name 'install.sh' -print);
  cdorexit $(dirname ${lfsscript});

  #FIXME ./install-git: line 29: Git: command not found
  $(${lfsscript});
  git lfs install;
  rm -rf "${tmp}";
}


function install_git_core() {
  install_from_manager "git-daemon-sysvinit"
  install_from_manager "git-all"
  
  git config --global credential.helper cache;
  git config --global alias.hist "log --all --graph --decorate --oneline --follow";
  
  # use environment variables instead
  # git config --global http.proxy "${http_proxy}";
  
  # install_from_manager "giggle"
  # smartgit only for non-commercial use
  # download "http://www.syntevo.com/static/smart/download/smartgit/smartgit-linux-17_0_4.tar.gz" "smartgit" "./bin/smartgit.sh" 
}

function main() {
  install_git_core "$@";
  install_git_lfs "$@";
}

main "$@"
