#!/bin/bash
source ./install.source.sh

function create_gimp_config_dir() {
  # Create user's gimp configuration directory
  local version minor_version; 
  version=$(gimp --version | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+$');
  minor_version=$(echo "${version}" | grep -Eo '^[0-9]+\.[0-9]+');
  if [ -z "${minor_version}" ]; then
    echo "[ERROR] Cannot determine gimp version">&2
    exit 1
  fi
  local -r configs=~/.gimp-${minor_version};
  mkdirorexit -p "${configs}";
  echo "${configs}";
}

function install_photoshop_pack() {
  local -r configs="${1:?[ERROR] gimp configuration directory not provided}";

  # Download PhotoShop Themes and Keyboard Shortcuts pack.
  local -r archive=$(wget_to_temp 'https://github.com/draekko/gimp-cc-themes/archive/master.zip');
  local -r tmp=$(dirname ${archive});
  unzip  "${archive}" -d "${tmp}";
  local -r master="${tmp}/gimp-cc-themes-master";
  
  # move keyborad shortcuts config
  mvorexit "${master}/ps_menurc" "${configs}/menurc";
  mvorexit ${master}/*.pdf "${configs}"
  
  # move themes
  local -r themes="${configs}/themes";
  mkdirorexit -p "${themes}";
  mvorexit ${master}/Gimp-CC-Theme-* "${themes}";
}

function congifure_preferences() {
  local -r configs="${1:?[ERROR] gimp configuration directory not provided}";
  
  # configure Preference
  local -r gimprc="${configs}/gimprc";
  echo '(undo-levels 50)' >> "${gimprc}";
  echo '(undo-size 250M)' >> "${gimprc}";
  echo '(thumbnail-size large)' >> "${gimprc}";
  echo '(thumbnail-filesize-limit 250M)' >> "${gimprc}";
  echo '(color-profile-policy convert)' >> "${gimprc}";
  echo '(transparency-size small-checks)' >> "${gimprc}";
  echo '(transparency-type light-checks)' >> "${gimprc}";
  echo '(max-new-image-size 250M)' >> "${gimprc}";
  echo '(theme "Gimp-CC-Theme-Darkest")' >> "${gimprc}";
  echo '(language "en_US")' >> "${gimprc}";
}

function install_layereffects() {
  local -r configs="${1:?[ERROR] gimp configuration directory not provided}";
  local -r plugins="${configs}/plug-ins";
  mkdirorexit -p "${plugins}";
  
  # install Layer Effects plugin
  local -r layerfx=$(wget_to_temp 'http://registry.gimp.org/files/layerfx.2.8.py.txt');
  chmod +x "${layerfx}";
  mvorexit "${layerfx}" "${plugins}/layerfx.py";
}

function install_photoeffects() {
  local -r configs="${1:?[ERROR] gimp configuration directory not provided}";
  local -r presets="${configs}/gimpressionist/presets";
  local -r scripts="${configs}/scripts";
  mkdirorexit -p "${presets}";
  mkdirorexit -p "${scripts}";

  # download
  local -r archive=$(wget_to_temp 'http://registry.gimp.org/files/ev_iccii_photoeffects_246c.zip');
  
  # uncompress
  local -r tmp=$(dirname ${archive});
  local -r photoeffects="${tmp}/photoeffects";
  mkdirorexit "${photoeffects}";
  unzip  "${archive}" -d "${photoeffects}";
  
  # move
  cdorexit "${photoeffects}";
  mvorexit Presets/* "${presets}";
  mvorexit *.scm "${scripts}";  
}

function main() {
  install_from_manager "gimp";
  local -r configs=$(create_gimp_config_dir);
  install_photoshop_pack "${configs}";
  install_photoshop_pack "${configs}";
  congifure_preferences "${configs}";
  
  # install plugins
  # Avesome Plugins: www.bloomtimes.com/gimp-plugins  
  install_layereffects "${configs}";
  install_photoeffects "${configs}";
  
  # install brushes and fonts
  ./install-gimp-brushes "${configs}/brushes"; 
  ./install-gimp-fonts "${configs}/fonts"; 
  
  # TODO: Configure Tools Settings
  #Move Tools
  #[*] Move the active layer
  #
  #Color Picker Tool
  #[X] Sample average (Radius=3)
  #
  #
  #Healing Tool
  #[X] Sample merged
  #Alignemtnt [Aligned]
  #
  #Crop Tool
  #[No guides] -> [Rule of thirds]
  #
  #Clone Tool
  #[X] Sample merged
  #Aligment [Aligned]
}

main "$@"